### ISSUE TITLE
Windowsize to small for 5+ devices

### ISSUE THREAD

**Issue by noestreich** [Sn0wfreezeDev/MenuBarControllerSonos#1]
If more than five Sonos-Devices are discovered in the network, the default window-size is to small to fit all the speakers in it. 
A draggable resize-option or a scrollable view could resolve this. 
<img width="288" alt="bildschirmfoto 2018-03-20 um 23 00 15" src="https://user-images.githubusercontent.com/309419/37685325-57c56894-2c93-11e8-966e-d7a37f3b2e15.png">

**Comment by Sn0wfreezeDev** [comment]
I added a scroll view in the develop branch
It would be nice if you could test it, because I'm currently on vacation

**Comment by Sn0wfreezeDev** [comment]
This issue was resolved with version 1.0.1
