### ISSUE TITLE
PLAY:5 Pair plus SUB appears as three separate speakers

### ISSUE THREAD

**Issue by pwt** [Sn0wfreezeDev/MenuBarControllerSonos#4]
As the title says. This applies to the version downloaded from the App Store on 2018-04-26.

![modified](https://user-images.githubusercontent.com/1089749/39294609-170ff59a-4934-11e8-8246-7976306bdfdc.png)

**Comment by Sn0wfreezeDev** [comment]
Hi Peter, 

This issue will be resolved in the next update (1.1.3) 
The Update will be submitted today (26.04.18) 

Regards, 
Alex

**Comment by pwt** [comment]
Thanks for this and the ongoing improvements to the App Store version. Are you planning to keep the GitHub codebase up to date?

**Comment by Sn0wfreezeDev** [comment]
Hey, 

the setup of the whole project has changed a lot and it currently needs also a server setup. 
I would like to update the code in GitHub, but I will have to add a lot of explanation to it. 
This will need some time, before I am able to share that

**Comment by pwt** [comment]
No problem, just curious. I'm enjoying the App Store version -- good work.

**Comment by pwt** [comment]
Fixed in the App Store version. Working very well; good work on the Sonos Cloud API integration.
